platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: 8.2-alpine

inputs:
  - name: source-code

caches:
  - path: source-code/node_modules

run:
  path: source-code/ci/tasks/install.sh