platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: 8.2-alpine

inputs:
  - name: source-code
  - name: npm-repo-cache
    path: node_modules

run:
  path: source-code/ci/tasks/test.sh