platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: '8.2-alpine'
inputs:
  - name: source-code
    path: source-code
  - name: npm-cache
    path: source-code/node_modules
run:
  path: npm
  args: ["test"]
  dir: source-code