resources:
  - name: source-code
    type: git
    source:
      uri: git@github.com:andybry/concourse-test.git
      branch: master
      private_key: ((private_key))

jobs:
  - name: test
    plan:
      - get: source-code
        trigger: true
      - task: test
        file: source-code/ci/tasks/test.yml