resources:
  - name: src
    type: git
    source:
      uri: git@github.com:andybry/concourse-test.git
      branch: master
      private_key: ((private_key))

jobs:
  - name: test
    plan:
      - get: src
        trigger: true
      - task: Task A
        file: src/ci/tasks/install.yml